#!/bin/bash -xv
mkdir -p ${OPENSHIFT_DATA_DIR}phantomjs/bin
cd ${OPENSHIFT_DATA_DIR}phantomjs/bin
export PATH=$PATH:${OPENSHIFT_DATA_DIR}phantomjs/bin
if [ ! -f phantomjs ]; then
   wget https://github.com/iiLaurens/openshift-selenium-phantomjs/releases/download/0.2/phantomjs2.0.0.tar.gz
   tar xf phantomjs2.0.0.tar.gz
   rm phantomjs2.0.0.tar.gz
   chmod +x phantomjs
fi